# Cleaning & Split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/TIH_IIT_Intern_Work/Dataset.csv")
df.head()

   S No  binary bit R  Binary bit S  Analog value  Analog Voltage     NTU
0     1             1             1           125        0.610352  1-2NTU
1     2             0             0           101        0.493164  1-2NTU
2     3             1             1           123        0.600586  1-2NTU
3     4             0             0           101        0.493164  1-2NTU
4     5             0             0            95        0.463867  1-2NTU

## 1. Dataset Shape

In [4]:
df.shape

(399, 6)

In [5]:
df.columns

Index(['S No', 'binary bit R', 'Binary bit S', 'Analog value',
       'Analog Voltage', 'NTU'],
      dtype='object')

## 2. Missing Values Audit

In [6]:
df.isnull().sum()

S No              0
binary bit R      0
Binary bit S      0
Analog value      0
Analog Voltage    0
NTU               0
dtype: int64

## 3.Duplicate Records

In [7]:
duplicate_count = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_count)

Total Duplicate Rows: 0

## 4. Invalid Bits

In [8]:
for col in ["binary bit R", "Binary bit S"]:
    if col in df.columns:
        invalid = df[~df[col].isin([0,1])]
        print(f"\nInvalid values in {col}: {len(invalid)}")

Invalid values in binary bit R: 0

Invalid values in Binary bit S: 0

## 5. Class Imbalance

In [9]:
print("\nCLASS BALANCE")
print(df["Binary bit S"].value_counts())
print("\nPercentage")
print(round(df["Binary bit S"].value_counts(normalize=True)*100,2))

CLASS BALANCE
Binary bit S
0    242
1    157
Name: count, dtype: int64

Percentage
Binary bit S
0    60.65
1    39.35
Name: proportion, dtype: float64

## 6. Outlier Detection

In [11]:
Q1 = df['Analog Voltage'].quantile(0.25)
Q3 = df['Analog Voltage'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Analog Voltage'] < lower_bound) | (df['Analog Voltage'] > upper_bound)]

print(f"Outliers in 'Analog Voltage' column (using IQR method):")
display(outliers)
print(f"Total number of outliers: {len(outliers)}")

Outliers in 'Analog Voltage' column (using IQR method):

     S No  binary bit R  Binary bit S  Analog value  Analog Voltage     NTU
0       1             1             1           125        0.610352  1-2NTU
2       3             1             1           123        0.600586  1-2NTU
6       7             1             1           142        0.693359  1-2NTU
10     11             1             1           124        0.605469  1-2NTU
11     12             1             1           144        0.703125  1-2NTU
..    ...           ...           ...           ...             ...     ...
381   382             0             0            74        0.361328  5-6NTU
389   390             0             0            73        0.356445  5-6NTU
396   397             0             0            72        0.351562  5-6NTU
397   398             0             0            74        0.361328  5-6NTU
398   399             0             1            72        0.351562  5-6NTU

[147 rows x 6 columns]

Total number of outliers: 147