# Data Quality & Class Audit

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/TIH_IIT_Intern_Work/Dataset.csv")
df.head()

   S No  binary bit R  Binary bit S  Analog value  Analog Voltage     NTU
0     1             1             1           125        0.610352  1-2NTU
1     2             0             0           101        0.493164  1-2NTU
2     3             1             1           123        0.600586  1-2NTU
3     4             0             0           101        0.493164  1-2NTU
4     5             0             0            95        0.463867  1-2NTU

## 1. Dataset Shape

In [ ]:
df.shape

(399, 6)

In [ ]:
df.columns

Index(['S No', 'binary bit R', 'Binary bit S', 'Analog value',
       'Analog Voltage', 'NTU'],
      dtype='object')

## 2. Missing Values Audit

In [ ]:
df.isnull().sum()

S No              0
binary bit R      0
Binary bit S      0
Analog value      0
Analog Voltage    0
NTU               0
dtype: int64

## 3.Duplicate Records

In [ ]:
duplicate_count = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_count)

Total Duplicate Rows: 0

## 4. Invalid Bits

In [ ]:
for col in ["binary bit R", "Binary bit S"]:
    if col in df.columns:
        invalid = df[~df[col].isin([0,1])]
        print(f"\nInvalid values in {col}: {len(invalid)}")

Invalid values in binary bit R: 0

Invalid values in Binary bit S: 0

## 5. Class Imbalance

In [ ]:
print("\nCLASS BALANCE")
print(df["Binary bit S"].value_counts())
print("\nPercentage")
print(round(df["Binary bit S"].value_counts(normalize=True)*100,2))

CLASS BALANCE
Binary bit S
0    242
1    157
Name: count, dtype: int64

Percentage
Binary bit S
0    60.65
1    39.35
Name: proportion, dtype: float64